FROM public.ecr.aws/d3j8x8q7/olympus-base-python:latest

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -e . \
 && pip install --no-cache-dir \
      "faker==40.36.0" \
      "typing-extensions==4.16.0" \
      "annotated-types==0.8.0" \
      "pydantic==2.13.4" \
      "pytest==9.1.1" \
      "pytest-asyncio==1.4.0"

RUN chmod -R a+rwX /app

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TZ=UTC

CMD ["/bin/bash"]