FROM public.ecr.aws/d3j8x8q7/olympus-base-jvm:latest

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

WORKDIR /app
COPY . .

RUN set -eux; \
    mkdir -p /opt/.m2/repository; \
    mvn -B -ntp -Dmaven.repo.local=/opt/.m2/repository -DskipTests clean install

RUN set -eux; \
    mvn -B -ntp -Dmaven.repo.local=/opt/.m2/repository dependency:get -Dartifact=org.apache.maven.surefire:surefire-junit-platform:3.5.3 -Dtransitive=true; \
    mvn -B -ntp -Dmaven.repo.local=/opt/.m2/repository dependency:get -Dartifact=org.junit.platform:junit-platform-launcher:1.9.0 -Dtransitive=true; \
    mvn -B -ntp -Dmaven.repo.local=/opt/.m2/repository dependency:get -Dartifact=org.junit.platform:junit-platform-launcher:1.9.2 -Dtransitive=true; \
    mvn -B -ntp -Dmaven.repo.local=/opt/.m2/repository dependency:get -Dartifact=org.junit.platform:junit-platform-launcher:6.0.2 -Dtransitive=true; \
    chmod -R a+rX /opt/.m2/repository; \
    mvn_conf="$(dirname "$(dirname "$(readlink -f "$(command -v mvn)")")")/conf/settings.xml"; \
    printf '%s\n' \
        '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">' \
        '  <localRepository>/opt/.m2/repository</localRepository>' \
        '  <offline>true</offline>' \
        '</settings>' > "$mvn_conf"; \
    chmod a+r "$mvn_conf"

ENV MAVEN_ARGS="-o -Dmaven.repo.local=/opt/.m2/repository"

CMD ["/bin/bash"]
