FROM public.ecr.aws/d3j8x8q7/olympus-base-jvm:latest
ENV MAVEN_USER_HOME=/opt/m2
ENV MAVEN_ARGS=-Dmaven.repo.local=/opt/m2/repository
WORKDIR /app
COPY . .
RUN mkdir -p /opt/m2/repository
RUN ./mvnw -B -ntp -version
RUN mvn -B -ntp dependency:get -Dartifact=com.fasterxml.jackson:jackson-bom:2.21.2:pom
RUN mvn -B -ntp dependency:get -Dartifact=tools.jackson:jackson-bom:3.1.0:pom
RUN mvn -B -ntp dependency:get -Dartifact=org.junit:junit-bom:5.9.1:pom
RUN mvn -B -ntp dependency:get -Dartifact=org.apache.maven.surefire:surefire-junit-platform:2.22.2
RUN mvn -B -ntp -DskipTests install
RUN mvn -B -ntp -DskipTests dependency:go-offline
RUN chmod -R a+rwX /opt/m2
CMD ["/bin/bash"]
