# GitHub account	Slot	Codespace name
Zeyad2003	primary	curly-adventure-wpjp69v54j2gx9
Zeyad-Nasef	primary	olympus-forge---zeyad-nasef-g44vv9gxpgxg29r69
ZeyadNasef	primary	olympus-forge---zeyadnasef-4qgw4qvq9qpgf7p7g
